name: 'Github Branch Release Drafter'
description: 'Drafts your next release notes from pull requests as they are merged into relevant branches'
runs:
  using: 'ubuntu-latest'
  image: 'Dockerfile'
branding:
  icon: droplet
  color: green
inputs:
  name:
    description: |
      The name that will be used in the GitHub release that's created or updated.
    required: false
  tag:
    description: |
      The tag name to be associated with the GitHub release that's created or updated.
    required: false
  version:
    description: |
      The version to be associated with the GitHub release that's created or updated.
    required: false
outputs:
  id:
    description: The ID of the release that was created or updated.
  name:
    description: The name of the release
  tag_name:
    description: The name of the tag associated with the release.
  body:
    description: The body of the drafted release.
